# Generated by Django 3.0.3 on 2020-03-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_file', models.FileField(upload_to='covid_data')),
                ('signature', models.TextField(unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('normalized', models.BooleanField(default=False)),
                ('process_detail', models.TextField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_state', models.CharField(blank=True, max_length=200, null=True, verbose_name='Province/State')),
                ('country_region', models.CharField(max_length=200, verbose_name='Country/Region')),
                ('last_update', models.DateTimeField(verbose_name='Last Update')),
                ('confirmed', models.FloatField(blank=True, null=True)),
                ('deaths', models.FloatField(blank=True, null=True)),
                ('recovered', models.FloatField(blank=True, null=True)),
                ('suspected', models.FloatField(blank=True, null=True)),
                ('confn_susp', models.FloatField(blank=True, null=True, verbose_name='Confirmed/Suspected')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('report_day', models.DateField(blank=True, null=True)),
                ('data_file_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
