# Generated by Django 3.0.3 on 2020-03-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='process_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
