# Generated by Django 3.0.3 on 2020-03-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200321_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='generaldata',
            name='confn_susp',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Confirmed/Suspected'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='process_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='data_file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='report_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
