# Generated by Django 3.0.3 on 2020-03-21 15:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datafile_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='header',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
