# Generated by Django 3.0.3 on 2020-03-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200321_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldata',
            name='confirmed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='confn_susp',
            field=models.FloatField(blank=True, null=True, verbose_name='Confirmed/Suspected'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='deaths',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='recovered',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='suspected',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
