# Generated by Django 3.0.3 on 2020-03-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200321_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldata',
            name='confirmed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='deaths',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='recovered',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
