# Generated by Django 3.0.3 on 2020-03-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200321_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldata',
            name='province_state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Province/State'),
        ),
    ]
